name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */4 * * *' #Executa a cada 4 horas 
  workflow_dispatch: #Execução Manual

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install selenium webdriver-manager

      - name: Executar Script de Wake Up
        run: python wake_up.py